import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import { EventsPage } from '../../../components/Event/EventsPage/EventsPage';
import { Slider } from '../../../components/Slider/Slider';
import { title } from '../../../components/Title/title';
import { store } from '../../../data/store';
import { eventsService } from '../../../services/events.service';

export async function getServerSideProps(context) {
  const { name, ...etc } = context.query;
  const { cookies } = context.req;
  const { take, skip } = store.eventsStore.fetchConfig;

  const search = etc.q;
  console.time('eventsInfoTheme');
  const eventsReq = await eventsService.getEvents(
    { take, skip, theme: name, name: search },
    {
      method: 'GET',
      headers: {
        Cookie: Object.entries(cookies)
          .map(([key, val]) => `${key}=${val}`)
          .join('; '),
      },
    },
  );

  console.timeLog('eventsInfoTheme', 'get');

  if (eventsReq.status === 404 || eventsReq.status === 400 || eventsReq.status === 500) {
    return {
      notFound: true,
    };
  }

  if (eventsReq.status === 401) {
    return {
      redirect: {
        permanent: false,
        destination: `/login`,
      },
      props: {},
    };
  }

  const events = (await eventsReq.json()) || { total: 0, data: [] };

  const filterParamsReq = await eventsService.getFilterParams(
    { theme: name },
    {
      method: 'GET',
      headers: {
        Cookie: Object.entries(cookies)
          .map(([key, val]) => `${key}=${val}`)
          .join('; '),
      },
    },
  );

  const filterParams = (await filterParamsReq.json()) || {};

  console.timeLog('eventsInfoTheme', 'filters');
  const promo = await eventsService.getPromoData(
    { location: 'story', skip: 0, take: 100 },
    {
      method: 'GET',
      headers: {
        Cookie: Object.entries(cookies)
          .map(([key, val]) => `${key}=${val}`)
          .join('; '),
      },
    },
  );

  console.timeLog('eventsInfoTheme', 'promo');
  console.timeEnd('eventsInfoTheme');

  return {
    props: {
      events,
      filterParams,
      promo,
    },
  };
}

export default function EventsTheme({ events = null, filterParams = null, promo = null }) {
  const router = useRouter();
  const { asPath } = router;
  if (events || filterParams) {
    store.eventsStore.setEvents(events, router.query.name);
    store.eventsStore.setFilterParams(filterParams, router.query.name);
    store.eventsStore.setFetchConfig({ format: null, type: null, payment: null, place: null });
  }

  useEffect(() => {
    const r = asPath.split('?');
    if (r.length > 0) {
      const params = new URLSearchParams(r[1]);
      if (params.has('q')) {
        store.eventsStore.setFetchConfig({ name: params.get('q') });
      }
    }
  }, [asPath]);

  return (
    <>
      <Head>
        <title>{title.titleText}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Slider promoData={promo} />
      <EventsPage />
    </>
  );
}
