import Head from 'next/head';
import React from 'react';
import { ContactsPanel } from '../../components/Contacts/ContactsPanel';
import { title } from '../../components/Title/title';

export default function Contacts() {
  return (
    <>
      <Head>
        <title>{title.titleText}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactsPanel />
    </>
  );
}
