'use client';

import Head from 'next/head';
import { useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { userService } from '../../services/user.service';
import { title } from '../../components/Title/title';

export default function Login() {
  const router = useRouter();

  useEffect(() => {
    const { email, password } = {
      email: 'content-user@gomeetup.ru',
      password: '12345678',
    };

    userService
      .login(email, password)
      .then(() => router.back())
      .catch(() => {});
  }, [router]);

  return (
    <Head>
      <title>{title.titleText}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
