import Head from 'next/head';
import { H2 } from '../../styles/blocks/Text';
import { EventCard } from '../../components/Event/EventCard/EventCard';
import { EventPageGrid } from '../../styles/blocks/EventGrid';
import { DetailEventBlock } from '../../styles/blocks/DetailEventBlock';
import { EventInfo } from '../../components/Event/EventInfo/EventInfo';
import { Tag2 } from '../../components/kit/Tag/Tag';
import { TagList } from '../../components/kit/Tag/TagList';
import { EventContent } from '../../components/Event/EventContent/EventContent';
import { ColFlexEvent } from '../../styles/blocks/Flex';
import {
  EventContainer,
  GradientLine,
  EventInfoContainer,
  ChainsWraper,
  BackgroundImage,
} from '../../styles/blocks/idStyled';
import { themeMatrix } from '../../helpers/themeMatrix';
import { title } from '../../components/Title/title';
import { eventsService } from '../../services/events.service';

export async function getServerSideProps(context) {
  const { id } = context.query;
  const { cookies } = context.req;

  console.time('eventInfo');
  const event = await eventsService.getEvent(id, {
    method: 'GET',
    headers: {
      Cookie: Object.entries(cookies)
        .map(([key, val]) => `${key}=${val}`)
        .join('; '),
    },
  });
  console.timeEnd('eventInfo');

  if (event.status === 404 || event.status === 400 || event.status === 500) {
    return {
      notFound: true,
    };
  }

  if (event.status === 401) {
    return {
      redirect: {
        permanent: false,
        destination: `/login`,
      },
      props: {},
    };
  }

  const eventData = (await event.json()) || {};

  const events = await eventsService.getEvents(
    { theme: eventData?.eventThemeTags?.length ? eventData.eventThemeTags[0]?.eventTheme?.name : 'other' },
    {
      method: 'GET',
      headers: {
        Cookie: Object.entries(cookies)
          .map(([key, val]) => `${key}=${val}`)
          .join('; '),
      },
    },
  );

  const { data: eventsList } = (await events.json()) || { data: [] };

  return {
    props: {
      eventData,
      eventsList,
    },
  };
}

export default function Event({ eventData = {}, eventsList = [] }) {
  const interestingEvents = eventsList.filter((item) => item.id !== eventData.id);
  return (
    <>
      <BackgroundImage />
      <Head>
        <title>{title.titleText}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DetailEventBlock>
        <ColFlexEvent eventPage>
          <GradientLine active />
          <EventContainer>
            <TagList row>
              {!eventData?.eventThemeTags?.length && <Tag2>{themeMatrix.other}</Tag2>}
              {eventData?.eventThemeTags?.map(({ eventTheme: { id, description, name } }) => {
                const isActive = name.toLowerCase() === 'selected';

                return (
                  <Tag2 key={id} active={isActive}>
                    {isActive ? 'Интересное' : description}
                  </Tag2>
                );
              })}
            </TagList>
            <EventContent eventStyle event={eventData} />
          </EventContainer>
        </ColFlexEvent>
        <EventInfoContainer>
          <EventInfo eventStyle event={eventData} />
          <ChainsWraper>
            {/* {[1, 2, 3].map((item) => (
              <ChainBlock key={item}>
                <GradientChainBlock>
                  <ChainIcon />
                </GradientChainBlock>
                <NormalTextBlock style={{ color: '#32344B' }} eventStyle>
                  Название материала
                </NormalTextBlock>
              </ChainBlock>
            ))} */}
          </ChainsWraper>
        </EventInfoContainer>
      </DetailEventBlock>
      <H2>Интересные события</H2>
      <EventPageGrid>
        {interestingEvents.map((e) => (
          <EventCard event={e} key={e.id} />
        ))}
      </EventPageGrid>
    </>
  );
}
