"use client";
//@ts-nocheck
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { EventsPage } from "../../../../components/Event/EventsPage/EventsPage";
import { Slider } from "../../../../components/Slider/Slider";
import { title } from "../../../../components/Title/title";
import { eventsService } from "../../../../services/events.service";
import { store } from "../../../../data/store";
import { Metadata } from "next";
import { useParams, usePathname, useRouter } from "next/navigation";
import { observer } from "mobx-react-lite";
import { advancedSearch } from '../../../../data/api/searchApi'

const Contacts = observer(() => {
  const [promo, setPromo] = useState(null);
  const params = useParams();
  const asPath = usePathname();
  const router = useRouter();

  useEffect(() => {
    const getEvents = async () => {
      const cookies = {


      };
      const { take, skip } = store.eventsStore._fetchConfig;

      console.time("eventsInfoTheme");

      store.eventsStore.fetchE
      advancedSearch(store.eventsStore._fetchConfig)

      const eventsReq = await eventsService.getEvents(
        { take, skip, theme: params.theme },
        {
          method: "GET",
          headers: {
            Cookie: Object.entries(cookies)
              .map(([key, val]) => `${key}=${val}`)
              .join("; "),
          },
        }
      );

      console.timeLog("eventsInfoTheme", "get");

      if (
        eventsReq.status === 404 ||
        eventsReq.status === 400 ||
        eventsReq.status === 500
      ) {
        return {
          notFound: true,
        };
      }

      if (eventsReq.status === 401) {
        router.push('/login')
        return {
          redirect: {
            permanent: false,
            destination: `/login`,
          },
          props: {},
        };
      }

      const events = (await eventsReq.json()) || { total: 0, data: [] };

      const filterParamsReq = await eventsService.getFilterParams(
        { theme: params.theme },
        {
          method: "GET",
          headers: {
            Cookie: Object.entries(cookies)
              .map(([key, val]) => `${key}=${val}`)
              .join("; "),
          },
        }
      );
      const filterParams = (await filterParamsReq.json()) || {};

      if (events || filterParams) {
        store.eventsStore.setEvents(events, null);
        store.eventsStore.setFilterParams(filterParams, params.theme);
        store.eventsStore.setFetchConfig({
          theme: params.theme,
          name: null,
          format: null,
          type: null,
          payment: null,
          place: null,
        });
      }
      console.timeLog("eventsInfoTheme", "filters");
      const promo = await eventsService.getPromoData(
        { location: "story", skip: 0, take: 100 },
        {
          method: "GET",
          headers: {
            Cookie: Object.entries(cookies)
              .map(([key, val]) => `${key}=${val}`)
              .join("; "),
          },
        }
      );
      setPromo(promo);
      console.timeLog("eventsInfoTheme", "promo");
      console.timeEnd("eventsInfoTheme");
    };

    console.log("getEvents();");

    getEvents();
  }, [params.theme]);

  useEffect(() => {
    const r = asPath.split("?");
    if (r.length > 0) {
      const params = new URLSearchParams(r[1]);
      if (params.has("q")) {
        store.eventsStore.setFetchConfig({ name: params.get("q") });
      }
    }
  }, [asPath]);

  return (
    <>
      {/* <Head>
        <title>{title.titleText}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <Slider promoData={promo} />
      <EventsPage />
    </>
  );
});

export default Contacts;
