import Head from 'next/head';
import React, { useEffect } from 'react';
import { EventsPage } from '../components/Event/EventsPage/EventsPage';
import { Slider } from '../components/Slider/Slider';
import { title } from '../components/Title/title';
import { eventsService } from '../services/events.service';
import { store } from '../data/store';

export async function getServerSideProps(context) {
  const { q } = context.query;
  const { cookies } = context.req;
  const { take, skip } = store.eventsStore.fetchConfig;

  console.time('eventsInfo');

  const eventsReq = await eventsService.getEvents(
    { take, skip, name: q },
    {
      method: 'GET',
      headers: {
        Cookie: Object.entries(cookies)
          .map(([key, val]) => `${key}=${val}`)
          .join('; '),
      },
    },
  );

  console.timeLog('eventsInfo', 'eventsGet');

  if (eventsReq.status === 404 || eventsReq.status === 400 || eventsReq.status === 500) {
    return {
      notFound: true,
    };
  }

  if (eventsReq.status === 401) {
    return {
      redirect: {
        permanent: false,
        destination: `/login`,
      },
      props: {},
    };
  }

  const events = (await eventsReq.json()) || { total: 0, data: [] };
  console.timeLog('eventsInfo', 'parce');

  const filterParamsReq = await eventsService.getFilterParams(null, {
    method: 'GET',
    headers: {
      Cookie: Object.entries(cookies)
        .map(([key, val]) => `${key}=${val}`)
        .join('; '),
    },
  });
  const filterParams = (await filterParamsReq.json()) || {};

  console.timeLog('eventsInfo', 'filters');
  const promo = await eventsService.getPromoData(
    { location: 'story', skip: 0, take: 100 },
    {
      method: 'GET',
      headers: {
        Cookie: Object.entries(cookies)
          .map(([key, val]) => `${key}=${val}`)
          .join('; '),
      },
    },
  );

  console.timeLog('eventsInfo', 'promo');
  console.timeEnd('eventsInfo');

  return {
    props: {
      events,
      filterParams,
      promo,
    },
  };
}

export default function Events({ events = null, filterParams = null, promo = null }) {
  if (events || filterParams) {
    store.eventsStore.setEvents(events, null);
    store.eventsStore.setFilterParams(
      // { ...filterParams, ...{ format: null, type: null, payment: null, place: null } },
      filterParams,
      null,
    );
    store.eventsStore.setFetchConfig({ format: null, type: null, payment: null, place: null });
  }

  useEffect(() => {
    // store.eventsStore.setFetchConfig({ name: '' });
  }, []);

  return (
    <>
      <Head>
        <title>{title.titleText}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Slider promoData={promo} />
      <EventsPage />
    </>
  );
}
