import Head from 'next/head';
import { title } from '../components/Title/title';

export default function News() {
  return (
    <Head>
      <title>{title.titleText}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
