name: Build

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, edited, ready_for_review ]
    branches:
      - 'master'

jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Build on Node 20.x
    runs-on: self-hosted
    container:
      image: node:20-alpine
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          show-progress: false
          clean: true

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
