name: Lint

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, edited, ready_for_review ]
    branches:
      - 'master'

jobs:
  lint:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Lint code
    runs-on: self-hosted
    container:
      image: node:20-alpine
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
