name: Release

on:
  push:
    branches:
      - 'master'
      - 'develop'
    tags:
      - '*'
    paths-ignore:
      - '.github/**'

jobs:
  build:
    name: Build and push to Dockerhub
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          show-progress: false
          clean: true

      - name: Get branch data
        run: |
          echo "SOURCE_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKERHUB_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_CLOUD_USERNAME }}
          password: ${{ secrets.DOCKERHUB_CLOUD_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        env:
          BRANCH: ${{ env.SOURCE_BRANCH }}
          BRANCH_NAME: ${{ env.SOURCE_NAME }}
          BRANCH_TAG: ${{ env.SOURCE_TAG }}
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_REGISTRY }}/gomeetup/meetup-frontend:${{ env.BRANCH_NAME }}


  deploy:
    needs: build
    name: Deploy to host
    runs-on: self-hosted
    steps:
      - name: Get branch data
        run: |
          echo "SOURCE_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Deploying changes
        uses: appleboy/ssh-action@master
        env:
          BRANCH: ${{ env.SOURCE_BRANCH }}
          BRANCH_NAME: ${{ env.SOURCE_NAME }}
          BRANCH_TAG: ${{ env.SOURCE_TAG }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_CLOUD_USERNAME }} -p ${{ secrets.DOCKERHUB_CLOUD_TOKEN }} ${{ secrets.DOCKERHUB_REGISTRY }}
            docker pull ${{ secrets.DOCKERHUB_REGISTRY }}/gomeetup/meetup-frontend:${{ env.BRANCH_NAME }}
            if [ "${{ env.BRANCH_NAME }}" == "master" ]; then
              cd meetup-deploy/master
              docker compose down -t 1 frontend && docker compose rm -f frontend
              docker compose up -d frontend
            elif [ "${{ env.BRANCH_NAME }}" == "develop" ]; then
              cd meetup-deploy/develop
              docker compose down -t 1 frontend-dev && docker compose rm -f frontend-dev
              docker compose up -d frontend-dev
            fi
